name: Build Extension

on:
  push:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: node --version

      - uses: oven-sh/setup-bun@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: bun install
      - name: Test
        run: bun test
      - name: Build
        run: bun run build
      - uses: actions/upload-artifact@v3
        with:
          name: built-extension
          path: dist/
